//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePassNatMsg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePassNatMsg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{
        ///  &quot;name&quot;: &quot;org.keepassxc.keepassxc_browser&quot;,
        ///  &quot;description&quot;: &quot;KeepassXC integration with Native Messaging support&quot;,
        ///  &quot;path&quot; : &quot;{0}&quot;,
        ///  &quot;type&quot;: &quot;stdio&quot;,
        ///  &quot;allowed_origins&quot;: [
        ///    &quot;chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/&quot;,
        ///    &quot;chrome-extension://oboonakemofpalcgghocfoadofidjkkk/&quot;
        ///  ]
        ///}}.
        /// </summary>
        internal static string chrome_win {
            get {
                return ResourceManager.GetString("chrome_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap earth_lock {
            get {
                object obj = ResourceManager.GetObject("earth_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{
        ///  &quot;name&quot;: &quot;org.keepassxc.keepassxc_browser&quot;,
        ///  &quot;description&quot;: &quot;KeepassXC integration with Firefox with Native Messaging support&quot;,
        ///  &quot;path&quot; : &quot;{0}&quot;,
        ///  &quot;type&quot;: &quot;stdio&quot;,
        ///  &quot;allowed_extensions&quot;: [
        ///    &quot;keepassxc-browser@keepassxc.org&quot;
        ///  ]
        ///}}.
        /// </summary>
        internal static string firefox_win {
            get {
                return ResourceManager.GetString("firefox_win", resourceCulture);
            }
        }
    }
}
